### ISSUE TITLE
Error when trying to visualize SF results in labbox-ephys

### ISSUE THREAD

**Issue by alejoe91** [flatironinstitute/spikeforest#4]
Hi guys, 

I got this error when launching labbox-ephys (v0.5.8):
```
Traceback (most recent call last):
  File "/Users/abuccino/bin/labbox-ephys", line 4, in <module>
    import labbox_ephys
  File "/Users/abuccino/anaconda3/envs/si/lib/python3.8/site-packages/labbox_ephys/__init__.py", line 12, in <module>
    from .helpers.prepare_snippets_h5 import (prepare_snippets_h5,
  File "/Users/abuccino/anaconda3/envs/si/lib/python3.8/site-packages/labbox_ephys/helpers/prepare_snippets_h5.py", line 12, in <module>
    image=hi.RemoteDockerImage('docker://magland/labbox-ephys-processing:0.3.19'),
TypeError: __init__() missing 1 required positional argument: 'tag'

```

**Comment by magland** [comment]
@alejoe91 
This should be resolved now if you upgrade the pip-installed hither package to version >=0.5.7

**Comment by alejoe91** [comment]
@magland somehow labbox-ephys starts but when I try to open the browser at the `http://localhost:14101/` port I get a "This site can’t be reached" page.

Sorry for the issue bombardment :P

**Comment by magland** [comment]
@alejoe91. thanks for submitting these issues - very helpful.

That port number doesn't seem right. I think you may not be on the latest version, which is currently 0.5.9. Can you confirm?

**Comment by alejoe91** [comment]
Hi @magland just upgraded it but still got the same issue. Now the port is: `http://localhost:15351`

Maybe something else is going on. Here is the full output:
```
(si) abuccino@bs-mbpr415 devel % labbox-ephys
/var/folders/vl/0vmqjsjn0dg8ycnxdx_mqrdw0000gr/T/kachery-tmp/tmp_shellscript__4j1exlz/script.sh: line 4: exec: serve: not found
Traceback (most recent call last):
  File "/Users/abuccino/anaconda3/envs/si/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 70, in <module>
    import cchardet as chardet
ModuleNotFoundError: No module named 'cchardet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/abuccino/bin/labbox_start_api_http", line 4, in <module>
    from aiohttp import web
  File "/Users/abuccino/anaconda3/envs/si/lib/python3.8/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import (
  File "/Users/abuccino/anaconda3/envs/si/lib/python3.8/site-packages/aiohttp/client.py", line 58, in <module>
    from .client_reqrep import (
  File "/Users/abuccino/anaconda3/envs/si/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 72, in <module>
    import chardet  # type: ignore
  File "/Users/abuccino/anaconda3/envs/si/lib/python3.8/site-packages/chardet-4.0.0-py3.8.egg/chardet/__init__.py", line 19, in <module>
    from .universaldetector import UniversalDetector
  File "/Users/abuccino/anaconda3/envs/si/lib/python3.8/site-packages/chardet-4.0.0-py3.8.egg/chardet/universaldetector.py", line 47, in <module>
    from .mbcsgroupprober import MBCSGroupProber
  File "/Users/abuccino/anaconda3/envs/si/lib/python3.8/site-packages/chardet-4.0.0-py3.8.egg/chardet/mbcsgroupprober.py", line 36, in <module>
    from .cp949prober import CP949Prober
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 914, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1342, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1314, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1467, in find_spec
KeyboardInterrupt
Please wait...
Open labbox-ephys in your browser: http://localhost:15351

```

**Comment by alejoe91** [comment]
I tried to `pip install cchardet`, but I still get a similar output:
```
(si) abuccino@bs-mbpr415 devel % labbox-ephys        
/var/folders/vl/0vmqjsjn0dg8ycnxdx_mqrdw0000gr/T/kachery-tmp/tmp_shellscript_crm2d27w/script.sh: line 4: exec: serve: not found
Traceback (most recent call last):
  File "/Users/abuccino/bin/labbox_start_api_http", line 4, in <module>
    from aiohttp import web
  File "/Users/abuccino/anaconda3/envs/si/lib/python3.8/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import (
  File "/Users/abuccino/anaconda3/envs/si/lib/python3.8/site-packages/aiohttp/client.py", line 58, in <module>
    from .client_reqrep import (
  File "/Users/abuccino/anaconda3/envs/si/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 70, in <module>
    import cchardet as chardet
  File "/Users/abuccino/anaconda3/envs/si/lib/python3.8/site-packages/cchardet/__init__.py", line 1, in <module>
    from cchardet import _cchardet
  File "<frozen importlib._bootstrap>", line 389, in parent
KeyboardInterrupt
Please wait...
Open labbox-ephys in your browser: http://localhost:15351
```

**Comment by magland** [comment]
i see that "serve" is not found. Didn't the instructions say to do `npm install -g serve`? Maybe i need to make the error message more helpful.

**Comment by alejoe91** [comment]
Haven't found that instruction step here: https://github.com/flatironinstitute/spikeforest/blob/main/doc/download-spikeforest-data.md

**Comment by alejoe91** [comment]
Installing `serve` fixed it. However I'm finding it a bit slower in loading the data as it was something like a month ago. I know you're heavily working on kachery + processing. 

As a comment to this, we almost have a working version of SpikeInterface1.0 (https://spikeinterface.github.io/blog/compare-old-vs-new-spikeinterface-api/). Performance-wise it's much faster than the previous version. We might want to discuss in the near future how to integrate the two projects.
